name: Titanic CI Pipeline

on:
  push:
    branches: [ main, develop ]  
  pull_request:
    branches: [ main, develop ]   

jobs:
  lint-test:               
    runs-on: ubuntu-latest 

    steps:

    # 1) Télécharger le code depuis GitHub
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2) Installer Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"     

    # 3) Installer toutes les dépendances du projet
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4) Vérifier le format du code (Black)
    - name: Run Black
      run: black --check .

    # 5) Vérifier la qualité du code (Flake8)
    - name: Run Flake8
      run: flake8 titanic_project --count --show-source --statistics

    # 6) Lancer les tests unitaires (Pytest)
    - name: Run Pytest
      run: pytest tests -v
